# MIT License
#
# Copyright (c) 2019 Thiago Alves
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
- name: "Check for {{ env.type }} version {{ version }} on {{ env.name }}"
  stat:
    path: "{{ env.install.datapath }}/versions/{{ version }}"
  register: env_version
  ignore_errors: yes
  when: not env.install.force

- name: "Install {{ env.type }} version {{ version }} on {{ env.name }}"
  raw: "SDKROOT=${SDKROOT:-{{ macOS_SDK_ROOT if macOS_SDK_ROOT is defined else '' }} } {{ env.name | upper }}_ROOT='{{ env.install.datapath }}' {{ _env.cmd }} install {{ version }}"
  notify: Rehash installed versions
  when: env_version is not defined or not env_version.stat.exists

- name: "Install {{ env.type }} version {{ version }} on {{ env.name }}"
  raw: "SDKROOT=${SDKROOT:-{{ macOS_SDK_ROOT if macOS_SDK_ROOT is defined else '' }} } {{ env.name | upper }}_ROOT='{{ env.install.datapath }}' {{ _env.cmd }} install {{ version }} --force"
  notify: Rehash installed versions
  when: env.install.force and env_version.stat.exists
